### ISSUE TITLE
Use ws protocol instead of wss when deploy to local

### ISSUE THREAD

**Issue by johnnyqian** [Azure-Samples/web-apps-node-iot-hub-data-visualization#11]
By default, when deploy to local environment, we do not use SSL. So, 
var ws = new WebSocket('wss://' + location.host); 
should be changed to:
var ws = new WebSocket('**ws**://' + location.host);

Otherwise, the following js error will be throw in browser:
WebSocket connection to 'wss://localhost:3000/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

**Comment by SLdragon** [comment]
Hi @johnnyqian , thanks for your suggestions, we will add some tips for local deployment.

**Comment by SLdragon** [comment]
https://github.com/Azure-Samples/web-apps-node-iot-hub-data-visualization/pull/14
