### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by hiropon413** [Azure-Samples/web-apps-node-iot-hub-data-visualization#12]
failed: Error during WebSocket handshake: Unexpected response code: 200
(anonymous) @ index.js:69
j @ jquery-2.1.4.min.js:2
fireWith @ jquery-2.1.4.min.js:2
ready @ jquery-2.1.4.min.js:2
I @ jquery-2.1.4.min.js:2

**Comment by hiropon413** [comment]
Error occurs in index.js " var ws = new WebSocket('wss://' + location.host)"  .

**Comment by drwill-ms** [comment]
I've significantly refactored the sample. Let me know if you see any issues with it.
