### ISSUE TITLE
Deploying to azure returns blank screen

### ISSUE THREAD

**Issue by Fenn-CS** [Azure-Samples/web-apps-node-iot-hub-data-visualization#17]
I followed the instructions on : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps

The website shows a blank screen and the logs from Kudu produces this, what's wrong?

> D:\home\site\wwwroot\node_modules\azure-event-hubs\dist\lib\rhea-promise\connection.js:141
    async createSender(options) {
          ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\azure-event-hubs\dist\lib\rhea-promise\index.js:16:20)
    at Module._compile (module.js:570:32)
Application has thrown an uncaught exception and is terminated:

**Comment by vslepakov** [comment]
had the same problem. the default node version seems to be a problem. I updated WEBSITE_NODE_DEFAULT_VERSION from 6.9.1 to 8.9.4 in the application settings and restarted the app. After a little while (update in progress) the application worked as expected.

This is the list of supported node versions on app service for windows:

{"nodejs":[{"version":"0.10.40","npm":"1.4.28"},{"version":"0.10.5","npm":"1.2.18"},{"version":"0.12.6","npm":"2.11.2"},{"version":"0.6.20","npm":"1.1.37"},{"version":"0.8.28","npm":"1.2.30"},{"version":"10.0.0","npm":"5.6.0"},{"version":"10.6.0","npm":"6.1.0"},{"version":"4.8.4","npm":"2.15.11"},{"version":"6.12.3","npm":"3.10.10"},{"version":"6.5.0","npm":"3.10.3"},{"version":"6.9.1","npm":"3.10.8"},{"version":"6.9.5","npm":"3.10.10"},{"version":"7.10.1","npm":"4.2.0"},{"version":"8.1.4","npm":"5.0.3"},{"version":"8.10.0","npm":"5.6.0"},{"version":"8.11.1","npm":"5.6.0"},{"version":"8.4.0","npm":"5.3.0"},{"version":"8.5.0","npm":"5.3.0"},{"version":"8.9.4","npm":"5.6.0"}],"system":{"os_name":"Windows Server 2016","os_build_lab_ex":"14393.2312.amd64fre.rs1_release(bryant).180609-2043","cores":1}}

**Comment by peterblazejewicz** [comment]
hi folks,
I've created the separate issue that describe the problem (due to other MS npm dependency):
https://github.com/Azure-Samples/web-apps-node-iot-hub-data-visualization/issues/19
Thanks!

**Comment by drwill-ms** [comment]
I've significantly refactored the sample and instructions. Please let us know if you see any issues.
