### ISSUE TITLE
Update application setup to use frozen deps version or migrate docs to support updated Node version

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure-Samples/web-apps-node-iot-hub-data-visualization#19]
The core dependency used by the sample as of version 0.2.1 was based solely on Promises in the implementation details:

https://github.com/Azure/azure-event-hubs-node/tree/v0.2.1-EH-May2018

In the 0.2.4 version the `azure-event-hubs` added undocumented use of async/await, which bumbed the minum required version of Node to 7.6:

https://github.com/Azure/azure-event-hubs-node/releases/tag/v0.2.4-EH-July2018
https://github.com/Azure/azure-event-hubs-node/blob/v0.2.4-EH-July2018/client/lib/rhea-promise/connection.ts#L179
https://github.com/Azure/azure-event-hubs-node/commit/d367b2a3bc6e2b06677516d57b09746c31a2ee43#diff-f2311358a38bc41bc8d4393e0c733a97R7

so they now compiling to runtime that expects support of async/await.

The problem is the Azure default Node version is 6.9.1, so this sample web app breaks either silently or with not widely known error for most users:
https://github.com/Azure-Samples/web-apps-node-iot-hub-data-visualization/issues/17
I've became aware of the issue via the IOT MVP list reported by other list member.

The quick fix for this app is:

```diff
diff --git a/package.json b/package.json
index 0746253..cb77421 100644
--- a/package.json
+++ b/package.json
@@ -6,7 +6,7 @@
     "start": "node server.js"
   },
   "dependencies": {
-    "azure-event-hubs": "^0.2.1",
+    "azure-event-hubs": "0.2.1",
     "express": "~4.14.1",
     "moment": "^2.17.1",
     "ws": "^2.1.0"
```

this fill froze the `azure-event-hub` version. Let me know if you want a hot fix issue that way

Thanks!

**Comment by amarzavery** [comment]
@peterblazejewicz - Is this windows app service or a linux app service?

**Comment by amarzavery** [comment]
Rather than taking a dependency on the old version of azure-event-hubs, I would recommend using the latest LTS version of node.js on the system. It should be simple to do that. You can follow the steps mentioned in this [issue comment](https://github.com/Azure/azure-event-hubs-node/issues/131#issuecomment-413255730)

**Comment by peterblazejewicz** [comment]
Great, I do understand and that's not my concern of being able to update Node version. I'm just concerned about the customers of the Azure that gets nothing from the sample run on the default web app settings. Hence I've created issue. Thanks!

**Comment by amarzavery** [comment]
I do understand the problem that you are trying to solve. However, I believe this is being solved in an incorrect manner by taking a strict dependency on a specific version of azure-event-hubs sdk.

IMHO, the correct fix would be to update the docs that indicate customers to deploy a webapp with an 8.x version of node.js.

**Comment by drwill-ms** [comment]
I've updated this to "@azure/event-hubs": "^2.0.0", and set the node value to >=10.6.
