### ISSUE TITLE
Deploy to Azure Web Apps Failed!

### ISSUE THREAD

**Issue by sanjayntms** [Azure-Samples/web-apps-node-iot-hub-data-visualization#20]
remote: Copying file: 'public\javascripts\index.js'
remote: Copying file: 'public\javascripts\jquery-2.1.4.min.js'
remote: Copying file: 'public\stylesheets\style.css'
remote: Using start-up script server.js from package.json.
remote: Generated web.config.
remote: The package.json file does not specify node.js engine version constraints.
remote: The node.js application will run with the default node.js version 0.10.40.
remote: Selected npm version 1.4.28
remote: ..
remote: npm WARN engine is-buffer@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
remote:
remote: > async-lock@1.1.3 postinstall D:\home\site\wwwroot\node_modules\azure-event-hubs\node_modules\async-lock
remote: >
remote:
remote: npm WARN engine request@2.88.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"1.4.28"})
remote: npm WARN engine har-validator@5.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
remote: npm WARN engine form-data@2.3.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
remote: npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"1.4.28"})
remote: .............
remote: npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
remote: .............
remote: npm ERR! Error: Method Not Allowed
remote: npm ERR!     at errorResponse (D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-named.js:260:10)
remote: npm ERR!     at D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-named.js:203:12
remote: npm ERR!     at saved (D:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\npm-registry-client\lib\get.js:167:7)
remote: npm ERR!     at Object.oncomplete (fs.js:108:15)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote:
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v0.10.40
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! code E405
remote: ........
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" install --production
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://ntmsiotweb.scm.azurewebsites.net:443/ntmsiotweb.git
 * [new branch]      master -> master

**Comment by amarzavery** [comment]
node version used on the web app is too old (0.10.40). Please use the latest LTS version (anything in 8.x.x) should be fine.

**Comment by Cannuh** [comment]
Hi,

Where do you exactly specify the new version to be used?

Thanks

**Comment by Cannuh** [comment]
Image to better illustrate how to go about this. 

[https://user-images.githubusercontent.com/37126106/45270467-967ea400-b452-11e8-8dc2-38f900e5c608.png](url)
