### ISSUE TITLE
azure app service does not support websockets.

### ISSUE THREAD

**Issue by mdparikh** [Azure-Samples/web-apps-node-iot-hub-data-visualization#23]
The recently changed interface for the Azure app service, has no way to configure the application to use Web sockets.
This node.js web application uses web sockets. But since the app service cannot be configured to use web sockets, the application fails.
This app was working fine earlier, before the recently changed app service configuration. Earlier, the web sockets configuration was possible in the "Application settings" page

**Comment by drwill-ms** [comment]
We've updated the sample, and confirmed Azure app service supports web sockets. It is in the UI and there is an Azure CLI to set it. If you have the chance, please run through the sample and give us any feedback.
