### ISSUE TITLE
 'connectionString' is a required parameter and must be of type: 'string'.

### ISSUE THREAD

**Issue by nithishk** [Azure-Samples/web-apps-node-iot-hub-data-visualization#35]
I had set the connection string and env variables in the launch.json in visual studio code.

When I debug I get the error

> webapp@0.0.1 start C:\Users\Nithish.Kalakonda\Desktop\web-apps-node-iot-hub-data-visualization
> node server.js

Listening on 3000.
'connectionString' is a required parameter and must be of type: 'string'.

**Comment by drwill-ms** [comment]
Hi nithishk -

Your launch.json should look like this. Does it?

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\server.js",
            "protocol": "inspector",
            "smartStep": true,
            "showAsyncStacks": true,
            "sourceMaps": true,
            "env": {
                "NODE_ENV": "local",
                "IotHubConnectionString": "HostName=redacted;SharedAccessKeyName=service;SharedAccessKey=redacted",
                "EventHubConsumerGroup": "monitoring"
            }
        }
    ]
}
```

Regards,
David

**Comment by nithishk** [comment]
Yes it does. I removed my ConnectionString here 👍 


{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\server.js",
            "protocol": "inspector",
            "smartStep": true,
            "showAsyncStacks": true,
            "sourceMaps": true,
            "env": {
               // "NODE_ENV": "local",
               // "IotHubConnectionString": "",
                //"EventHubConsumerGroup": "gobconsum"
            }
        }
    ]
}

**Comment by drwill-ms** [comment]
In your json snippet above, the 3 env properties are remarked out. Can you confirm if you get the error with the slashes removed?

**Comment by nithishk** [comment]
yes I do

**Comment by nithishk** [comment]
Seems I have used wrong connection string from device instead of the HUB

**Comment by drwill-ms** [comment]
Thanks Nithishk. Let us know if you run into any other problems with the sample, or if you think it could be improved in any way.
