### ISSUE TITLE
Unable to open the amqp connection

### ISSUE THREAD

**Issue by JianpingCAI** [Azure-Samples/web-apps-node-iot-hub-data-visualization#38]
I met an error after running 'npm start', 

`Listening on 3000.
Unable to open the amqp connection "connection-1" due to operation timeout.`

launch.json is correctly set with the required 'IotHubConnectionString' and 'EventHubConsumerGroup'. 
Please advise. Thanks.

**Comment by drwill-ms** [comment]
Hi @JianpingCAI, I loaded the project with my variables and did not repro your issue. Does it still repro for you? I suspect there might have been a temporary service issue with your iot or event hub.

While I was here, I noticed an npm package vulnerability warning, so I updated packages. With a major version bump in event hub package, it changed the interface, which uses a different connection string. Perhaps you can checkout my [PR branch](https://github.com/Azure-Samples/web-apps-node-iot-hub-data-visualization/pull/39) and try it out?

**Comment by JianpingCAI** [comment]
Hi @drwill-ms , thanks a lot for the prompt response. 

Yes, I still can reproduce the issue with the master branch. Here are the steps I have done,
- IoTHub and an IoT device are created successfully;
- A 'Raspberry Pi Azure IoT Online Simulator' is connected successfully to the IoTHub;
- Modify launch.json, filling-in the 'IotHubConnectionString' and 'EventHubConsumerGroup';
- Run 'npm install', and 'npm start';
- Got the amqp connection error.

With your branch, I got an error of 'connection string malformed', as below, 
`> node server.js
Connection string malformed: each part of the connection string must have an `=` assignment.
Listening on 3000.`
Here, not sure about the 'IotHubEventHubConnectionString' in your changes, so I still use the same IotHub connection string as the first case. 

Thanks again for your help.

**Comment by JianpingCAI** [comment]
Hi, @drwill-ms, I tested it with AZURE IOT HUB extension in vs code, and a same error occurs when 'start monitoring built-in event endpoint'. So the issue is not caused by the sample code here, but I have no idea how to fix it for now.

`[IoTHubMonitor] Start monitoring message arrived in built-in endpoint for all devices ...
[IoTHubMonitor] MessagingError: Unable to open the amqp connection "connection-1" due to operation timeout.`

**Comment by drwill-ms** [comment]
@JianpingCAI are you running `npm start` from the integrated terminal in VSCode? If not, you'll need to set the environment variables in the console where you type that command.

You might also try F5 (debug) in VSCode. That makes use of launch.json environment variables.

**Comment by drwill-ms** [comment]
@JianpingCAI  I'm testing a few additional scenarios and getting the error you described in some cases. I'm seeing what I can do to resolve that.

In the meantime, try using F5 debug in VSCode. I know that works. :)

**Comment by drwill-ms** [comment]
I realized I was setting the environment variables wrong in powershell, which gave me the same error you saw:

> node server.js Connection string malformed: each part of the connection string must have an = assignment. Listening on 3000.

How are you setting your environment variables? I needed to type `$env:IotHubConnectionString` (or in my branch it is renamed to `IotHubEventHubConnectionString`).

**Comment by JianpingCAI** [comment]
> @JianpingCAI are you running `npm start` from the integrated terminal in VSCode? If not, you'll need to set the environment variables in the console where you type that command.
> 
> You might also try F5 (debug) in VSCode. That makes use of launch.json environment variables.

@drwill-ms Yes, you are right, F5 VSCode is working after I created a new iothub. Thanks a lot!

**Comment by JianpingCAI** [comment]
> I realized I was setting the environment variables wrong in powershell, which gave me the same error you saw:
> 
> > node server.js Connection string malformed: each part of the connection string must have an = assignment. Listening on 3000.
> 
> How are you setting your environment variables? I needed to type `$env:IotHubConnectionString` (or in my branch it is renamed to `IotHubEventHubConnectionString`).

@drwill-ms The setting is done in the launch.json file in VSCode.

**Comment by drwill-ms** [comment]
From my testing, I did not find that values in launch.json were getting picked up if typing `npm start` in the console. I don't think it has that integration.

**Comment by Hasnni** [comment]
iam getting same problem Unable open amqp connection. 
how can i set my environment variables. can you tell me steps thanks
