### ISSUE TITLE
web app doesn't work with SimulatedTemperatureSensor 

### ISSUE THREAD

**Issue by jh-isw** [Azure-Samples/web-apps-node-iot-hub-data-visualization#41]
Hello,
to get this sample to work with IoT Edge SimulatedTemperatureSensor-Module, I had to change the field access as in PR #40 
It prepends `.ambient` to `.temperature` and `.humidity` in the callback function.
This was already added with an earlier PR and overridden by a commit from Sept. 04th 2019.
(e1377fe071b8826ae7c8d178cfcc2a3fba26c62c)

In case this is wanted, just reject my PR and close the issue.

Best regards,
Jan

**Comment by drwill-ms** [comment]
Hi Jan -

Thank you for your contribution. :)

That change would make this sample incompatible with the [existing documentation instructions](https://docs.microsoft.com/en-us/samples/azure-samples/web-apps-node-iot-hub-data-visualization/web-app-visualization/) to use a different telemetry source. We don't want to break the existing sample, and we want to maintain the ease with which the sample can be run.

However, I am open to making the code capable of reading from either schema. One trade-off to that approach is that it will make this sample code more complex and harder to read, so we'd want to make sure any changes we make are very clear, documented, and easy to read.

If you are interested in submitting an update to your PR with those goals in mind, I will certainly consider it.

All the best,
David
