### ISSUE TITLE
[CXP] WebApp not displaying any data

### ISSUE THREAD

**Issue by asergaz** [Azure-Samples/web-apps-node-iot-hub-data-visualization#46]
Moving thread here to help fix the issue raised on Docs.
From Customer issue: https://github.com/MicrosoftDocs/azure-docs/issues/53901

> Hello,
> I'm using an Arduino board to send temperature and humidity data on my Azure Web App.
Everything is working locally, but when migrating to Azure WebApp I have no device to display anymore.
> I commented 'return' in chart-device-data.js to make it work locally (as suggested in the issue #[52495](https://github.com/MicrosoftDocs/azure-docs/issues/52495))
I tried to change the data model (as suggested in issue #[37707](https://github.com/MicrosoftDocs/azure-docs/issues/37707)) but it didn't work.
> I've noted that when migrating to Azure, 1 line was automatically deleted: "myLineChart.update();"
Do you know why and if the issue could come from this?
> Thank you in advance !

**Comment by asergaz** [comment]
fyi @teapotestac

**Comment by drwill-ms** [comment]
@teapotestac 

I noticed when I ran through the steps, my IoT Hub connection string was stored incorrectly if I did not wrap it in quotation marks. Can you inspect your webapp app settings to ensure these two values are set and are accurate? You can run `az webapp config appsettings list -n <web app name> -g <rg name>` to see them.

- EventHubConsumerGroup
- IotHubConnectionString

**Comment by teapotestac** [comment]
@drwill-ms it worked !! Thank you very much.
I wonder why it did work on the localhost with this wrong setting, but whatever it's working now on WebApp with this new change!

**Comment by drwill-ms** [comment]
What change did you make?

**Comment by teapotestac** [comment]
The IotHubConnectionString was not stored correctly.
I reset it and wrapped it in quotation mark

**Comment by drwill-ms** [comment]
Gotcha. I'll look to get our instructions updated to help others avoid that problem.

Thanks!
