### ISSUE TITLE
App stops reading messages after a while

### ISSUE THREAD

**Issue by ddewaele** [Azure-Samples/web-apps-node-iot-hub-data-visualization#5]
I noticed that after some time the app simply stops reading messages (even though devices are still sending messages).

Restarting the app causes messages to be read again.

**Comment by HITliuyu** [comment]
I confirm this issue is existing. Have no idea what caused this issue but I really hope Azure engineer can fix it soon. This simple app is quite useful in many use cases which do not require a nice UI. And as a simple application used in the tutorial, you'd better make sure it works fine.

**Comment by Aalwattar** [comment]
I  confirm this issue as well. 
I guess it's related to 
https://github.com/Azure/azure-event-hubs-node/issues/30

**Comment by suleymanov** [comment]
Faced same issue -- app stops sending messages after 20 mins, restart helps. We're preparing an MVP right now, so it would be nice if MS Azure crew showed how to fix it if possible, as it doesn't seem proper to me to permanently restart the app during the presentation...

**Comment by suleymanov** [comment]
@yuwzho Hi should we expect comment on issue or try other approaches?

**Comment by yuwzho** [comment]
@SLdragon Would you please take care of this issue?

**Comment by amarzavery** [comment]
Whoever is maintaining the sample for event hubs in this repo, please make sure to use the latest version of azure-event-hubs library. It was rewritten from scratch. Hopefully the above issue should not occur. You can find examples for writing apps against the new version over [here](https://github.com/Azure/azure-event-hubs-node/tree/master/client#examples).
