### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by anandmg101** [Azure-Samples/web-apps-node-iot-hub-data-visualization#6]
I followed the tutorial but getting HTTP ERROR 500. On the tutorial page one commenter noted it is because of server.js fails due to passing insufficient parameters to the library.

Any fix for this issue?

**Comment by WilliamFrasson** [comment]
same problem HTTP ERROR 500

**Comment by ngunderson** [comment]
I encountered this issue as well. Deleting my app and following https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps exactly solved my issue, ensuring to turn on the web socket config. I believe something got messed up when I turned python on, and then forced my git push of this repo the first time. Turning python off had no effect.

**Comment by kheiakiyama** [comment]
I had a same problem.
My web app plan is free.
Node version is `v0.10.40`.
But when I changed node version, it works!
App settings, key: `WEBSITE_NODE_DEFAULT_VERSION ` value: `8.9.4`

**Comment by drwill-ms** [comment]
I've fixed the node issues by upgrading to the latest version, and specifying that version in package.json.
