### ISSUE TITLE
after npm start webSocket.Server fails

### ISSUE THREAD

**Issue by WilliamFrasson** [Azure-Samples/web-apps-node-iot-hub-data-visualization#7]
D:\home\site\wwwroot\server.js:16
const wss = new WebSocket.Server({ server });
                                          ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! webapp@0.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the webapp@0.0.0 start script.
npm ERR! This is most likely a problem with the webapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls webapp
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

**Comment by drwill-ms** [comment]
I've updated to the latest version of node and do not see this error. Can you let us know if you see the issue any more?
